/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RegionSelectorRouteImport } from './routes/region-selector'
import { Route as QrCodeGeneratorRouteImport } from './routes/qr-code-generator'
import { Route as ApiReferenceRouteImport } from './routes/api-reference'
import { Route as IndexRouteImport } from './routes/index'
import { Route as WatchTogetherIndexRouteImport } from './routes/watch-together/index'
import { Route as SteamLookupChar123QueryChar125RouteImport } from './routes/steam-lookup.{-$query}'
import { Route as OpenProfileSteamidRouteImport } from './routes/open-profile.$steamid'
import { Route as WatchTogetherRoomRoomidRouteImport } from './routes/watch-together/room.$roomid'
import { Route as ApiResolveQueryRouteImport } from './routes/api/resolve.$query'
import { Route as ApiLookupSteamidRouteImport } from './routes/api/lookup.$steamid'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth.$'

const RegionSelectorRoute = RegionSelectorRouteImport.update({
  id: '/region-selector',
  path: '/region-selector',
  getParentRoute: () => rootRouteImport,
} as any)
const QrCodeGeneratorRoute = QrCodeGeneratorRouteImport.update({
  id: '/qr-code-generator',
  path: '/qr-code-generator',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiReferenceRoute = ApiReferenceRouteImport.update({
  id: '/api-reference',
  path: '/api-reference',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const WatchTogetherIndexRoute = WatchTogetherIndexRouteImport.update({
  id: '/watch-together/',
  path: '/watch-together/',
  getParentRoute: () => rootRouteImport,
} as any)
const SteamLookupChar123QueryChar125Route =
  SteamLookupChar123QueryChar125RouteImport.update({
    id: '/steam-lookup/{-$query}',
    path: '/steam-lookup/{-$query}',
    getParentRoute: () => rootRouteImport,
  } as any)
const OpenProfileSteamidRoute = OpenProfileSteamidRouteImport.update({
  id: '/open-profile/$steamid',
  path: '/open-profile/$steamid',
  getParentRoute: () => rootRouteImport,
} as any)
const WatchTogetherRoomRoomidRoute = WatchTogetherRoomRoomidRouteImport.update({
  id: '/watch-together/room/$roomid',
  path: '/watch-together/room/$roomid',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiResolveQueryRoute = ApiResolveQueryRouteImport.update({
  id: '/api/resolve/$query',
  path: '/api/resolve/$query',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiLookupSteamidRoute = ApiLookupSteamidRouteImport.update({
  id: '/api/lookup/$steamid',
  path: '/api/lookup/$steamid',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/api-reference': typeof ApiReferenceRoute
  '/qr-code-generator': typeof QrCodeGeneratorRoute
  '/region-selector': typeof RegionSelectorRoute
  '/open-profile/$steamid': typeof OpenProfileSteamidRoute
  '/steam-lookup/{-$query}': typeof SteamLookupChar123QueryChar125Route
  '/watch-together/': typeof WatchTogetherIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/lookup/$steamid': typeof ApiLookupSteamidRoute
  '/api/resolve/$query': typeof ApiResolveQueryRoute
  '/watch-together/room/$roomid': typeof WatchTogetherRoomRoomidRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/api-reference': typeof ApiReferenceRoute
  '/qr-code-generator': typeof QrCodeGeneratorRoute
  '/region-selector': typeof RegionSelectorRoute
  '/open-profile/$steamid': typeof OpenProfileSteamidRoute
  '/steam-lookup/{-$query}': typeof SteamLookupChar123QueryChar125Route
  '/watch-together': typeof WatchTogetherIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/lookup/$steamid': typeof ApiLookupSteamidRoute
  '/api/resolve/$query': typeof ApiResolveQueryRoute
  '/watch-together/room/$roomid': typeof WatchTogetherRoomRoomidRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/api-reference': typeof ApiReferenceRoute
  '/qr-code-generator': typeof QrCodeGeneratorRoute
  '/region-selector': typeof RegionSelectorRoute
  '/open-profile/$steamid': typeof OpenProfileSteamidRoute
  '/steam-lookup/{-$query}': typeof SteamLookupChar123QueryChar125Route
  '/watch-together/': typeof WatchTogetherIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/lookup/$steamid': typeof ApiLookupSteamidRoute
  '/api/resolve/$query': typeof ApiResolveQueryRoute
  '/watch-together/room/$roomid': typeof WatchTogetherRoomRoomidRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/api-reference'
    | '/qr-code-generator'
    | '/region-selector'
    | '/open-profile/$steamid'
    | '/steam-lookup/{-$query}'
    | '/watch-together/'
    | '/api/auth/$'
    | '/api/lookup/$steamid'
    | '/api/resolve/$query'
    | '/watch-together/room/$roomid'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/api-reference'
    | '/qr-code-generator'
    | '/region-selector'
    | '/open-profile/$steamid'
    | '/steam-lookup/{-$query}'
    | '/watch-together'
    | '/api/auth/$'
    | '/api/lookup/$steamid'
    | '/api/resolve/$query'
    | '/watch-together/room/$roomid'
  id:
    | '__root__'
    | '/'
    | '/api-reference'
    | '/qr-code-generator'
    | '/region-selector'
    | '/open-profile/$steamid'
    | '/steam-lookup/{-$query}'
    | '/watch-together/'
    | '/api/auth/$'
    | '/api/lookup/$steamid'
    | '/api/resolve/$query'
    | '/watch-together/room/$roomid'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ApiReferenceRoute: typeof ApiReferenceRoute
  QrCodeGeneratorRoute: typeof QrCodeGeneratorRoute
  RegionSelectorRoute: typeof RegionSelectorRoute
  OpenProfileSteamidRoute: typeof OpenProfileSteamidRoute
  SteamLookupChar123QueryChar125Route: typeof SteamLookupChar123QueryChar125Route
  WatchTogetherIndexRoute: typeof WatchTogetherIndexRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiLookupSteamidRoute: typeof ApiLookupSteamidRoute
  ApiResolveQueryRoute: typeof ApiResolveQueryRoute
  WatchTogetherRoomRoomidRoute: typeof WatchTogetherRoomRoomidRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/region-selector': {
      id: '/region-selector'
      path: '/region-selector'
      fullPath: '/region-selector'
      preLoaderRoute: typeof RegionSelectorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/qr-code-generator': {
      id: '/qr-code-generator'
      path: '/qr-code-generator'
      fullPath: '/qr-code-generator'
      preLoaderRoute: typeof QrCodeGeneratorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api-reference': {
      id: '/api-reference'
      path: '/api-reference'
      fullPath: '/api-reference'
      preLoaderRoute: typeof ApiReferenceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/watch-together/': {
      id: '/watch-together/'
      path: '/watch-together'
      fullPath: '/watch-together/'
      preLoaderRoute: typeof WatchTogetherIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/steam-lookup/{-$query}': {
      id: '/steam-lookup/{-$query}'
      path: '/steam-lookup/{-$query}'
      fullPath: '/steam-lookup/{-$query}'
      preLoaderRoute: typeof SteamLookupChar123QueryChar125RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/open-profile/$steamid': {
      id: '/open-profile/$steamid'
      path: '/open-profile/$steamid'
      fullPath: '/open-profile/$steamid'
      preLoaderRoute: typeof OpenProfileSteamidRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/watch-together/room/$roomid': {
      id: '/watch-together/room/$roomid'
      path: '/watch-together/room/$roomid'
      fullPath: '/watch-together/room/$roomid'
      preLoaderRoute: typeof WatchTogetherRoomRoomidRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/resolve/$query': {
      id: '/api/resolve/$query'
      path: '/api/resolve/$query'
      fullPath: '/api/resolve/$query'
      preLoaderRoute: typeof ApiResolveQueryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/lookup/$steamid': {
      id: '/api/lookup/$steamid'
      path: '/api/lookup/$steamid'
      fullPath: '/api/lookup/$steamid'
      preLoaderRoute: typeof ApiLookupSteamidRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ApiReferenceRoute: ApiReferenceRoute,
  QrCodeGeneratorRoute: QrCodeGeneratorRoute,
  RegionSelectorRoute: RegionSelectorRoute,
  OpenProfileSteamidRoute: OpenProfileSteamidRoute,
  SteamLookupChar123QueryChar125Route: SteamLookupChar123QueryChar125Route,
  WatchTogetherIndexRoute: WatchTogetherIndexRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiLookupSteamidRoute: ApiLookupSteamidRoute,
  ApiResolveQueryRoute: ApiResolveQueryRoute,
  WatchTogetherRoomRoomidRoute: WatchTogetherRoomRoomidRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
